services:
- type: web
  name: odr-langgraph
  env: python
  plan: free
  autoDeploy: true

  buildCommand: |
    pip install uv
    uv sync --frozen

  startCommand: |
    uvx --refresh --from "langgraph-cli[inmem]" --python 3.11 \
      langgraph dev --host 0.0.0.0 --port $PORT --allow-blocking

  envVars:
    - key: OPENAI_API_KEY
      sync: false
    - key: TAVILY_API_KEY
      sync: false
    - key: LANGCHAIN_API_KEY
      sync: false
    - key: LANGCHAIN_TRACING_V2
      value: "true"
    - key: LANGCHAIN_ENDPOINT
      value: "https://api.smith.langchain.com"
    - key: LANGCHAIN_PROJECT
      value: "odr-prod"

